# Generated by Django 2.1.15 on 2021-03-06 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('authorization_code', models.TextField()),
                ('scopes', models.TextField()),
                ('access_token', models.TextField()),
                ('expires_in', models.IntegerField()),
                ('refresh_token', models.TextField()),
                ('x_refresh_token_expires_in', models.IntegerField()),
                ('id_token', models.TextField()),
                ('token_type', models.CharField(choices=[('BR', 'Bearer')], default='BR', max_length=2)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('integration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Integration')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
