# Generated by Django 2.1.15 on 2021-03-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='access_token',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='authorization_code',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='client_id',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='client_secret',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='expires_in',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='id_token',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='refresh_token',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='scopes',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='x_refresh_token_expires_in',
            field=models.IntegerField(default=None),
        ),
    ]
