# Generated by Django 2.1.15 on 2021-03-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210307_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='realm_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
