# Generated by Django 2.1.15 on 2021-03-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_account_realm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='error_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='error_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
