# Generated by Django 2.1.15 on 2021-03-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210308_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='error_date',
            new_name='error_at',
        ),
    ]
