# Generated by Django 2.1.15 on 2021-03-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210308_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='client_secret',
        ),
        migrations.AddField(
            model_name='integration',
            name='client_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='client_secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
